import { Course, Exam } from './types'

export const COURSES: Course[] = [
  {
    id: 'course-1',
    title: 'Mathematics Class 10',
    description: 'Complete mathematics course for Class 10 CBSE',
    category: 'Class 9-10',
    level: 'Intermediate',
    instructor: 'Dr. Rajesh Kumar',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh',
    thumbnail: 'https://images.unsplash.com/photo-1509228627152-72ae67a36d11?w=500&h=300&fit=crop',
    rating: 4.8,
    ratingCount: 2450,
    studentsCount: 12500,
    price: 499,
    originalPrice: 999,
    chapters: [
      {
        id: 'ch-1-1',
        title: 'Number Systems',
        description: 'Learn about different number systems and their properties',
        duration: 45,
      },
      {
        id: 'ch-1-2',
        title: 'Polynomials',
        description: 'Understanding polynomials and their roots',
        duration: 50,
      },
      {
        id: 'ch-1-3',
        title: 'Linear Equations',
        description: 'Solving linear equations in two variables',
        duration: 55,
      },
    ],
    description_long: 'Master Class 10 Mathematics with comprehensive lessons covering all CBSE topics. Learn from experienced educators with clear explanations and practice problems.',
    learnings: [
      'Master all CBSE Class 10 Math topics',
      'Solve complex problems with confidence',
      'Score 95+ in board exams',
      'Build strong mathematical foundation',
    ],
    requirements: [
      'Basic knowledge of Class 9 Mathematics',
      'Notebook and pen for practice',
      'Internet connection for video lessons',
    ],
    createdAt: '2024-01-15',
    updatedAt: '2024-03-12',
  },
  {
    id: 'course-2',
    title: 'Science Class 10',
    description: 'Comprehensive science course covering Physics, Chemistry, and Biology',
    category: 'Class 9-10',
    level: 'Intermediate',
    instructor: 'Prof. Meena Singh',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Meena',
    thumbnail: 'https://images.unsplash.com/photo-1530587191325-3db8b1e1b6d8?w=500&h=300&fit=crop',
    rating: 4.7,
    ratingCount: 1980,
    studentsCount: 10200,
    price: 599,
    originalPrice: 1199,
    chapters: [
      {
        id: 'ch-2-1',
        title: 'Motion and Forces',
        description: 'Understanding Newton\'s laws and motion',
        duration: 60,
      },
      {
        id: 'ch-2-2',
        title: 'Waves and Sound',
        description: 'Properties of waves and sound phenomena',
        duration: 50,
      },
      {
        id: 'ch-2-3',
        title: 'Electricity and Magnetism',
        description: 'Fundamentals of electricity and magnetic effects',
        duration: 65,
      },
    ],
    description_long: 'Complete Class 10 Science course with engaging videos and interactive experiments. Cover Physics, Chemistry, and Biology with real-world examples.',
    learnings: [
      'Understand all science concepts clearly',
      'Perform virtual experiments safely',
      'Excel in board examinations',
      'Develop scientific thinking',
    ],
    requirements: [
      'Curiosity and willingness to learn',
      'Paper for notes and drawings',
      'Access to computer for videos',
    ],
    createdAt: '2024-01-20',
    updatedAt: '2024-03-12',
  },
  {
    id: 'course-3',
    title: 'JEE Main Mathematics',
    description: 'Advanced mathematics for JEE Main preparation',
    category: 'JEE',
    level: 'Advanced',
    instructor: 'Amit Sharma',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amit',
    thumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=500&h=300&fit=crop',
    rating: 4.9,
    ratingCount: 3200,
    studentsCount: 18500,
    price: 1299,
    originalPrice: 2499,
    chapters: [
      {
        id: 'ch-3-1',
        title: 'Calculus - Limits',
        description: 'Understanding limits and continuity',
        duration: 75,
      },
      {
        id: 'ch-3-2',
        title: 'Derivatives',
        description: 'Differentiation and applications',
        duration: 80,
      },
      {
        id: 'ch-3-3',
        title: 'Integrals',
        description: 'Integration techniques and applications',
        duration: 85,
      },
    ],
    description_long: 'Crack JEE Main with our advanced mathematics course. Cover all topics with problem-solving strategies and shortcuts.',
    learnings: [
      'Master all JEE Math topics',
      'Learn problem-solving shortcuts',
      'Score 90+ in JEE Main',
      'Build competitive exam readiness',
    ],
    requirements: [
      'Class 12 Mathematics knowledge',
      'Strong foundation in Class 11',
      'Dedication and consistency',
    ],
    createdAt: '2024-02-01',
    updatedAt: '2024-03-12',
  },
  {
    id: 'course-4',
    title: 'NEET Biology',
    description: 'Complete Biology course for NEET preparation',
    category: 'NEET',
    level: 'Advanced',
    instructor: 'Dr. Priya Patel',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    thumbnail: 'https://images.unsplash.com/photo-1576091160550-112173f7f869?w=500&h=300&fit=crop',
    rating: 4.8,
    ratingCount: 2800,
    studentsCount: 15600,
    price: 1499,
    originalPrice: 2999,
    chapters: [
      {
        id: 'ch-4-1',
        title: 'Cell Structure and Function',
        description: 'Understanding cellular organization',
        duration: 70,
      },
      {
        id: 'ch-4-2',
        title: 'Genetics and Evolution',
        description: 'Heredity, variation and evolution',
        duration: 75,
      },
      {
        id: 'ch-4-3',
        title: 'Human Physiology',
        description: 'Body systems and their functions',
        duration: 80,
      },
    ],
    description_long: 'Master NEET Biology with detailed explanations and memory techniques. Cover all NEET-level topics systematically.',
    learnings: [
      'Understand complex biological concepts',
      'Remember difficult topics easily',
      'Score 320+ in NEET Biology',
      'Build medical knowledge foundation',
    ],
    requirements: [
      'Class 12 Biology basics',
      'Willingness to study regularly',
      'Access to diagrams and models',
    ],
    createdAt: '2024-02-10',
    updatedAt: '2024-03-12',
  },
  {
    id: 'course-5',
    title: 'English Language Skills',
    description: 'Improve your English grammar, vocabulary, and communication skills',
    category: 'Class 11-12',
    level: 'Intermediate',
    instructor: 'Sarah Williams',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    thumbnail: 'https://images.unsplash.com/photo-1457369804613-52c0ee648d93?w=500&h=300&fit=crop',
    rating: 4.6,
    ratingCount: 1650,
    studentsCount: 8900,
    price: 399,
    originalPrice: 799,
    chapters: [
      {
        id: 'ch-5-1',
        title: 'Grammar Fundamentals',
        description: 'Master English grammar basics',
        duration: 55,
      },
      {
        id: 'ch-5-2',
        title: 'Vocabulary Building',
        description: 'Expand your English vocabulary',
        duration: 50,
      },
      {
        id: 'ch-5-3',
        title: 'Communication Skills',
        description: 'Effective speaking and writing',
        duration: 60,
      },
    ],
    description_long: 'Improve your English communication skills with practical lessons and exercises. Perfect for school, college, and competitive exams.',
    learnings: [
      'Master English grammar completely',
      'Build a strong vocabulary',
      'Communicate confidently',
      'Excel in English exams',
    ],
    requirements: [
      'Basic English knowledge',
      'Dictionary (online or offline)',
      'Practice notebook',
    ],
    createdAt: '2024-02-15',
    updatedAt: '2024-03-12',
  },
]

export const EXAMS: Exam[] = [
  {
    id: 'exam-1',
    title: 'Class 10 Mathematics - Mock Test 1',
    description: 'Full-length mock test for Class 10 Mathematics CBSE board exam',
    category: 'Class 9-10',
    difficulty: 'Medium',
    duration: 120,
    totalQuestions: 40,
    passingScore: 70,
    maxScore: 100,
    questions: [
      {
        id: 'q-1-1',
        question: 'What is the nature of roots of the quadratic equation 4x² - 12x + 9 = 0?',
        options: ['Real and distinct', 'Real and equal', 'Imaginary', 'Cannot be determined'],
        correctAnswer: 1,
        explanation: 'The discriminant = b² - 4ac = 144 - 144 = 0, so roots are real and equal',
        difficulty: 'easy',
      },
      {
        id: 'q-1-2',
        question: 'If the sum of first n terms of an AP is n²p + np, where p is a constant, then find the common difference?',
        options: ['2p', 'p', '-p', '-2p'],
        correctAnswer: 0,
        explanation: 'Sn = n²p + np, so d = S1 - S0 = p + p = 2p for n > 1',
        difficulty: 'medium',
      },
      {
        id: 'q-1-3',
        question: 'In a circle with center O, if angle AOB = 60°, then angle ACB (where C is a point on the circle) is:',
        options: ['30°', '60°', '120°', '90°'],
        correctAnswer: 0,
        explanation: 'Angle subtended at center is twice the angle subtended at circumference',
        difficulty: 'medium',
      },
      {
        id: 'q-1-4',
        question: 'Find the value of k for which the quadratic equation has equal roots: kx² - 4x + 1 = 0',
        options: ['4', '2', '-4', '-2'],
        correctAnswer: 1,
        explanation: 'For equal roots, discriminant = 0. So 16 - 4k = 0, k = 4',
        difficulty: 'hard',
      },
      {
        id: 'q-1-5',
        question: 'What is the distance between the points (3, 4) and (0, 0)?',
        options: ['3', '4', '5', '7'],
        correctAnswer: 2,
        explanation: 'Distance = √(3² + 4²) = √(9 + 16) = √25 = 5',
        difficulty: 'easy',
      },
      {
        id: 'q-1-6',
        question: 'Two lines are perpendicular if the product of their slopes is:',
        options: ['0', '1', '-1', '∞'],
        correctAnswer: 2,
        explanation: 'For perpendicular lines, m₁ × m₂ = -1',
        difficulty: 'easy',
      },
      {
        id: 'q-1-7',
        question: 'What is the sum of angles in a pentagon?',
        options: ['360°', '540°', '720°', '900°'],
        correctAnswer: 1,
        explanation: 'Sum of interior angles = (n-2) × 180° = (5-2) × 180° = 540°',
        difficulty: 'easy',
      },
      {
        id: 'q-1-8',
        question: 'If sin θ = 3/5, find cos θ (where θ is acute):',
        options: ['4/5', '3/5', '1/5', '5/4'],
        correctAnswer: 0,
        explanation: 'Using sin²θ + cos²θ = 1: (3/5)² + cos²θ = 1, cos²θ = 16/25, cos θ = 4/5',
        difficulty: 'medium',
      },
      {
        id: 'q-1-9',
        question: 'Which of the following is an irrational number?',
        options: ['22/7', '√4', '√5', '3.14'],
        correctAnswer: 2,
        explanation: '√5 cannot be expressed as a ratio of two integers, making it irrational',
        difficulty: 'medium',
      },
      {
        id: 'q-1-10',
        question: 'Find the median of the data: 3, 5, 7, 2, 8',
        options: ['2', '5', '7', '8'],
        correctAnswer: 1,
        explanation: 'When arranged in order: 2, 3, 5, 7, 8. Median is the middle value = 5',
        difficulty: 'easy',
      },
    ],
    createdAt: '2024-01-15',
    updatedAt: '2024-03-12',
  },
  {
    id: 'exam-2',
    title: 'JEE Main Mathematics - Practice Test',
    description: 'Practice test covering important JEE Main Mathematics topics',
    category: 'JEE',
    difficulty: 'Hard',
    duration: 180,
    totalQuestions: 30,
    passingScore: 80,
    maxScore: 100,
    questions: [
      {
        id: 'q-2-1',
        question: 'Let f(x) = x³ - 3x + 2. Find the number of real roots of f(x) = 0',
        options: ['1', '2', '3', '0'],
        correctAnswer: 2,
        explanation: 'f(x) = (x-1)²(x+2), so roots are 1 (double root) and -2. Total 3 real roots.',
        difficulty: 'hard',
      },
      {
        id: 'q-2-2',
        question: 'If ∫sin(x)dx from 0 to π/2 = a, then ∫cos(x)dx from 0 to π/2 =',
        options: ['a', '-a', '0', '2a'],
        correctAnswer: 0,
        explanation: 'Both integrals equal 1 by substitution property of definite integrals',
        difficulty: 'medium',
      },
      {
        id: 'q-2-3',
        question: 'In a matrix equation AX = B, if A is non-singular, then X =',
        options: ['AB', 'B/A', 'A⁻¹B', 'BA⁻¹'],
        correctAnswer: 2,
        explanation: 'Multiply both sides by A⁻¹ on the left: A⁻¹AX = A⁻¹B, so X = A⁻¹B',
        difficulty: 'medium',
      },
      {
        id: 'q-2-4',
        question: 'The value of lim(x→0) (sin x)/x is:',
        options: ['0', '1', '∞', '-1'],
        correctAnswer: 1,
        explanation: 'This is a standard limit, lim(x→0) (sin x)/x = 1',
        difficulty: 'easy',
      },
      {
        id: 'q-2-5',
        question: 'If f\'(x) = 2x + 3, then f(x) =',
        options: ['x² + 3x + C', '2x² + 3x + C', 'x² + 3 + C', '2x + 3 + C'],
        correctAnswer: 0,
        explanation: 'Integrating: f(x) = ∫(2x + 3)dx = x² + 3x + C',
        difficulty: 'medium',
      },
      {
        id: 'q-2-6',
        question: 'The equation of the tangent to y = x² at point (1, 1) is:',
        options: ['y = 2x - 1', 'y = x', 'y = 2x', 'y = x + 1'],
        correctAnswer: 0,
        explanation: 'dy/dx = 2x, at x=1: slope = 2. Equation: y - 1 = 2(x - 1) → y = 2x - 1',
        difficulty: 'medium',
      },
    ],
    createdAt: '2024-02-01',
    updatedAt: '2024-03-12',
  },
  {
    id: 'exam-3',
    title: 'NEET Biology - Chapter Test',
    description: 'Chapter-wise test for NEET Biology preparation',
    category: 'NEET',
    difficulty: 'Hard',
    duration: 180,
    totalQuestions: 45,
    passingScore: 75,
    maxScore: 100,
    questions: [
      {
        id: 'q-3-1',
        question: 'Which of the following is NOT a function of mitochondria?',
        options: ['ATP production', 'Heat generation', 'Photosynthesis', 'Calcium storage'],
        correctAnswer: 2,
        explanation: 'Photosynthesis occurs in chloroplasts, not mitochondria',
        difficulty: 'easy',
      },
      {
        id: 'q-3-2',
        question: 'The process of programmed cell death is called:',
        options: ['Necrosis', 'Apoptosis', 'Autophagy', 'Lysis'],
        correctAnswer: 1,
        explanation: 'Apoptosis is controlled, programmed cell death. Others are uncontrolled or degradative',
        difficulty: 'medium',
      },
      {
        id: 'q-3-3',
        question: 'Meiosis II is similar to which process?',
        options: ['Meiosis I', 'Mitosis', 'Cytokinesis', 'Fertilization'],
        correctAnswer: 1,
        explanation: 'Meiosis II has similar stages to mitosis but with haploid cells',
        difficulty: 'medium',
      },
      {
        id: 'q-3-4',
        question: 'Which organelle is responsible for protein synthesis?',
        options: ['Golgi apparatus', 'Ribosome', 'Endoplasmic reticulum', 'Lysosome'],
        correctAnswer: 1,
        explanation: 'Ribosomes are the site of protein synthesis in the cell',
        difficulty: 'easy',
      },
      {
        id: 'q-3-5',
        question: 'The genetic code is read in groups of:',
        options: ['1 nucleotide', '2 nucleotides', '3 nucleotides', '4 nucleotides'],
        correctAnswer: 2,
        explanation: 'The genetic code is read in triplets called codons, each specifying an amino acid',
        difficulty: 'medium',
      },
      {
        id: 'q-3-6',
        question: 'Which of the following is an autosomal dominant disorder?',
        options: ['Hemophilia', 'Color blindness', 'Huntington disease', 'Cystic fibrosis'],
        correctAnswer: 2,
        explanation: 'Huntington disease is caused by autosomal dominant inheritance',
        difficulty: 'hard',
      },
      {
        id: 'q-3-7',
        question: 'Photosynthesis primarily occurs in which organelle?',
        options: ['Mitochondria', 'Chloroplast', 'Nucleus', 'Ribosome'],
        correctAnswer: 1,
        explanation: 'Chloroplasts contain chlorophyll and are the site of photosynthesis',
        difficulty: 'easy',
      },
      {
        id: 'q-3-8',
        question: 'The enzyme that unwinds the DNA double helix during replication is:',
        options: ['DNA polymerase', 'Helicase', 'Ligase', 'Primase'],
        correctAnswer: 1,
        explanation: 'Helicase breaks hydrogen bonds between base pairs to unwind DNA',
        difficulty: 'medium',
      },
    ],
    createdAt: '2024-02-10',
    updatedAt: '2024-03-12',
  },
]

export function getCourseById(id: string): Course | undefined {
  return COURSES.find((course) => course.id === id)
}

export function getExamById(id: string): Exam | undefined {
  return EXAMS.find((exam) => exam.id === id)
}

export function getCoursesByCategory(category: string): Course[] {
  return COURSES.filter((course) => course.category === category)
}

export function getExamsByCategory(category: string): Exam[] {
  return EXAMS.filter((exam) => exam.category === category)
}
