import { Course, Exam } from './types'

export const COURSES: Course[] = [
  {
    id: 'course-1',
    title: 'Sales Fundamentals 101',
    description: 'Master the core principles of successful selling and customer engagement.',
    category: 'Sales Training',
    level: 'Beginner',
    instructor: 'Rajesh Kumar',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
    rating: 4.8,
    ratingCount: 245,
    studentsCount: 1250,
    price: 0,
    originalPrice: 0,
    chapters: [
      {
        id: 'ch-1-1',
        title: 'Introduction to Sales',
        description: 'Understanding the sales mindset and core principles',
        duration: 45,
      },
      {
        id: 'ch-1-2',
        title: 'Building Rapport',
        description: 'How to connect with prospects and build trust',
        duration: 50,
      },
      {
        id: 'ch-1-3',
        title: 'The Sales Process',
        description: 'Understanding each stage of the sales cycle',
        duration: 55,
      },
    ],
    description_long: 'Master the fundamentals of sales with this comprehensive course designed for the Shikshanation sales team. Learn proven techniques for prospecting, presenting, and closing deals.',
    learnings: [
      'Understand the complete sales cycle',
      'Build lasting customer relationships',
      'Master discovery and qualification',
      'Develop a winning sales mindset',
    ],
    requirements: [
      'No prior sales experience required',
      'Willingness to practice and role-play',
      'Access to training materials',
    ],
    createdAt: '2024-01-15',
    updatedAt: '2024-03-12',
  },
  {
    id: 'course-2',
    title: 'Product Knowledge Mastery',
    description: 'Deep dive into all Shikshanation products, features, and value propositions.',
    category: 'Product Training',
    level: 'Intermediate',
    instructor: 'Priya Sharma',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    thumbnail: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=500&h=300&fit=crop',
    rating: 4.9,
    ratingCount: 198,
    studentsCount: 980,
    price: 0,
    originalPrice: 0,
    chapters: [
      {
        id: 'ch-2-1',
        title: 'Product Overview',
        description: 'Complete overview of Shikshanation product suite',
        duration: 60,
      },
      {
        id: 'ch-2-2',
        title: 'Feature Deep Dive',
        description: 'Detailed walkthrough of key features and benefits',
        duration: 75,
      },
      {
        id: 'ch-2-3',
        title: 'Competitive Positioning',
        description: 'How we compare to competitors and our unique value',
        duration: 50,
      },
    ],
    description_long: 'Become an expert on all Shikshanation products. This course covers features, benefits, pricing, and competitive positioning to help you sell with confidence.',
    learnings: [
      'Master all product features',
      'Articulate value propositions clearly',
      'Handle competitive comparisons',
      'Match products to customer needs',
    ],
    requirements: [
      'Basic understanding of EdTech industry',
      'Access to product demo environment',
      'Completed Sales Fundamentals course',
    ],
    createdAt: '2024-01-20',
    updatedAt: '2024-03-12',
  },
  {
    id: 'course-3',
    title: 'Advanced Closing Techniques',
    description: 'Learn proven techniques to close more deals and overcome objections.',
    category: 'Sales Training',
    level: 'Advanced',
    instructor: 'Amit Patel',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amit',
    thumbnail: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=500&h=300&fit=crop',
    rating: 4.7,
    ratingCount: 156,
    studentsCount: 720,
    price: 0,
    originalPrice: 0,
    chapters: [
      {
        id: 'ch-3-1',
        title: 'Psychology of Closing',
        description: 'Understanding buyer psychology and decision-making',
        duration: 65,
      },
      {
        id: 'ch-3-2',
        title: 'Objection Handling',
        description: 'Techniques for handling common objections',
        duration: 70,
      },
      {
        id: 'ch-3-3',
        title: 'Closing Strategies',
        description: 'Multiple closing techniques for different situations',
        duration: 60,
      },
    ],
    description_long: 'Take your closing skills to the next level. Learn advanced techniques for handling objections, creating urgency, and sealing the deal with confidence.',
    learnings: [
      'Master multiple closing techniques',
      'Handle any objection with confidence',
      'Create genuine urgency',
      'Increase your close rate significantly',
    ],
    requirements: [
      'At least 3 months sales experience',
      'Completed Sales Fundamentals course',
      'Active participation in role-plays',
    ],
    createdAt: '2024-02-01',
    updatedAt: '2024-03-12',
  },
  {
    id: 'course-4',
    title: 'CRM & Sales Tools Training',
    description: 'Master our CRM system and sales tools for maximum productivity.',
    category: 'Tools Training',
    level: 'Beginner',
    instructor: 'Sneha Reddy',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sneha',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&h=300&fit=crop',
    rating: 4.6,
    ratingCount: 134,
    studentsCount: 890,
    price: 0,
    originalPrice: 0,
    chapters: [
      {
        id: 'ch-4-1',
        title: 'CRM Basics',
        description: 'Getting started with our CRM system',
        duration: 40,
      },
      {
        id: 'ch-4-2',
        title: 'Pipeline Management',
        description: 'Managing your sales pipeline effectively',
        duration: 45,
      },
      {
        id: 'ch-4-3',
        title: 'Reporting & Analytics',
        description: 'Using reports to track and improve performance',
        duration: 50,
      },
    ],
    description_long: 'Learn to use our CRM and sales tools effectively. This course covers everything from basic navigation to advanced reporting and automation.',
    learnings: [
      'Navigate the CRM with confidence',
      'Manage your pipeline effectively',
      'Track your performance metrics',
      'Automate repetitive tasks',
    ],
    requirements: [
      'CRM account setup completed',
      'Basic computer skills',
      'Access to training environment',
    ],
    createdAt: '2024-02-10',
    updatedAt: '2024-03-12',
  },
  {
    id: 'course-5',
    title: 'Consultative Selling',
    description: 'Transform from order-taker to trusted advisor with consultative selling.',
    category: 'Sales Training',
    level: 'Intermediate',
    instructor: 'Vikram Singh',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vikram',
    thumbnail: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=500&h=300&fit=crop',
    rating: 4.8,
    ratingCount: 178,
    studentsCount: 650,
    price: 0,
    originalPrice: 0,
    chapters: [
      {
        id: 'ch-5-1',
        title: 'Discovery Excellence',
        description: 'Asking the right questions to uncover needs',
        duration: 55,
      },
      {
        id: 'ch-5-2',
        title: 'Solution Mapping',
        description: 'Matching solutions to customer challenges',
        duration: 50,
      },
      {
        id: 'ch-5-3',
        title: 'Value Articulation',
        description: 'Presenting value in customer terms',
        duration: 45,
      },
    ],
    description_long: 'Move beyond transactional selling to become a trusted advisor. Learn to uncover real needs, present tailored solutions, and build long-term customer relationships.',
    learnings: [
      'Conduct effective discovery calls',
      'Identify hidden customer needs',
      'Present solutions that resonate',
      'Build long-term relationships',
    ],
    requirements: [
      'Completed Sales Fundamentals course',
      'Basic product knowledge',
      'Willingness to practice discovery calls',
    ],
    createdAt: '2024-02-15',
    updatedAt: '2024-03-12',
  },
]

export const EXAMS: Exam[] = [
  {
    id: 'exam-1',
    title: 'Sales Fundamentals Assessment',
    description: 'Test your knowledge of core sales principles and techniques',
    category: 'Sales Training',
    difficulty: 'Easy',
    duration: 30,
    totalQuestions: 20,
    passingScore: 70,
    maxScore: 100,
    questions: [
      {
        id: 'q-1-1',
        question: 'What is the first step in the sales process?',
        options: ['Closing', 'Prospecting', 'Presentation', 'Negotiation'],
        correctAnswer: 1,
        explanation: 'Prospecting is always the first step - finding potential customers before anything else.',
        difficulty: 'easy',
      },
      {
        id: 'q-1-2',
        question: 'Which technique is most effective for building rapport?',
        options: ['Talking about yourself', 'Active listening', 'Rushing to pitch', 'Avoiding questions'],
        correctAnswer: 1,
        explanation: 'Active listening shows genuine interest and helps build trust with prospects.',
        difficulty: 'easy',
      },
      {
        id: 'q-1-3',
        question: 'What does "qualifying" a prospect mean?',
        options: ['Giving them a test', 'Determining if they are a good fit', 'Checking their credit', 'Sending them brochures'],
        correctAnswer: 1,
        explanation: 'Qualifying helps determine if the prospect has the need, budget, and authority to buy.',
        difficulty: 'medium',
      },
      {
        id: 'q-1-4',
        question: 'The best way to handle objections is to:',
        options: ['Argue with the customer', 'Ignore them', 'Acknowledge and address them', 'Change the subject'],
        correctAnswer: 2,
        explanation: 'Acknowledging objections shows respect and addressing them builds trust.',
        difficulty: 'medium',
      },
      {
        id: 'q-1-5',
        question: 'What is a "discovery call"?',
        options: ['Cold calling random numbers', 'A call to understand customer needs', 'A pricing discussion', 'A follow-up call'],
        correctAnswer: 1,
        explanation: 'Discovery calls are designed to understand the customer\'s situation, needs, and goals.',
        difficulty: 'easy',
      },
    ],
    createdAt: '2024-01-15',
    updatedAt: '2024-03-12',
  },
  {
    id: 'exam-2',
    title: 'Product Knowledge Quiz',
    description: 'Test your understanding of Shikshanation products and features',
    category: 'Product Training',
    difficulty: 'Medium',
    duration: 45,
    totalQuestions: 25,
    passingScore: 75,
    maxScore: 100,
    questions: [
      {
        id: 'q-2-1',
        question: 'What is Shikshanation\'s primary target market?',
        options: ['Corporate training', 'K-12 education', 'University students', 'Government institutions'],
        correctAnswer: 1,
        explanation: 'Shikshanation focuses primarily on K-12 students preparing for board exams and competitive tests.',
        difficulty: 'easy',
      },
      {
        id: 'q-2-2',
        question: 'Which feature differentiates us from competitors?',
        options: ['Lower price only', 'Personalized learning paths', 'More videos', 'Larger class sizes'],
        correctAnswer: 1,
        explanation: 'Our AI-powered personalized learning paths adapt to each student\'s pace and needs.',
        difficulty: 'medium',
      },
      {
        id: 'q-2-3',
        question: 'What is included in the premium plan?',
        options: ['Video access only', 'All features plus live doubt solving', 'Basic worksheets', 'Just exam papers'],
        correctAnswer: 1,
        explanation: 'Premium includes all features plus unlimited live doubt solving sessions.',
        difficulty: 'medium',
      },
    ],
    createdAt: '2024-02-01',
    updatedAt: '2024-03-12',
  },
  {
    id: 'exam-3',
    title: 'Advanced Closing Assessment',
    description: 'Evaluate your mastery of advanced closing techniques',
    category: 'Sales Training',
    difficulty: 'Hard',
    duration: 60,
    totalQuestions: 30,
    passingScore: 80,
    maxScore: 100,
    questions: [
      {
        id: 'q-3-1',
        question: 'When a prospect says "I need to think about it", you should:',
        options: ['End the call immediately', 'Probe to understand their concerns', 'Offer a bigger discount', 'Ignore and close anyway'],
        correctAnswer: 1,
        explanation: 'This often signals an unaddressed concern that needs to be uncovered and resolved.',
        difficulty: 'hard',
      },
      {
        id: 'q-3-2',
        question: 'The "assumptive close" technique involves:',
        options: ['Assuming they won\'t buy', 'Acting as if they\'ve already decided to buy', 'Assuming you know their needs', 'Making assumptions about budget'],
        correctAnswer: 1,
        explanation: 'Assumptive close moves forward as if the decision has been made, helping hesitant buyers.',
        difficulty: 'medium',
      },
      {
        id: 'q-3-3',
        question: 'Creating urgency is best done by:',
        options: ['Making up fake deadlines', 'Highlighting genuine time-sensitive value', 'Pressuring repeatedly', 'Threatening price increases'],
        correctAnswer: 1,
        explanation: 'Authentic urgency based on real value or timing is effective and ethical.',
        difficulty: 'hard',
      },
    ],
    createdAt: '2024-02-10',
    updatedAt: '2024-03-12',
  },
]

export function getCourseById(id: string): Course | undefined {
  return COURSES.find((course) => course.id === id)
}

export function getExamById(id: string): Exam | undefined {
  return EXAMS.find((exam) => exam.id === id)
}

export function getCoursesByCategory(category: string): Course[] {
  return COURSES.filter((course) => course.category === category)
}

export function getExamsByCategory(category: string): Exam[] {
  return EXAMS.filter((exam) => exam.category === category)
}
